/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_PC.h"
#include "UART_PC_SPI_UART.h"
#include "UART_PC_PINS.h"
#include "UART_PC_SPI_UART_PVT.h"
#include "UART_PC_PVT.h"
#include "UART_PC_BOOT.h"
#include "Pin_DS18B20_DQ.h"
#include "Pin_DS18B20_DQ_aliases.h"
#include "UART_PC_SCBCLK.h"
#include "UART_PC_tx.h"
#include "UART_PC_tx_aliases.h"
#include "UART_PC_SCB_IRQ.h"
#include "UART_PC_rx.h"
#include "UART_PC_rx_aliases.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

